HarrierApp/Controllers/NewScreenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HarrierApp.Controllers
{
    public class NewScreenController : Controller
    {
        // GET: NewScreen
        public ActionResult Index()
        {
            return View();
        }
    }
}

HarrierApp/Controllers/RegisterController.cs
using HarrierApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Text;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;

namespace HarrierApp.Controllers
{
    public class RegisterController : Controller
    {


        DbServices dbServices = new DbServices();
        // GET: Register
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult SaveData(UserAuthModel user)
        {
            try
            {
                user.IsValid = false;
                dbServices.AddUserAuth(user);
                Console.WriteLine("Login User Saved into DB=" + user.Id);
                // BuildEmailTemplate(user.Id);
                return Json("Registration Successfull" , JsonRequestBehavior.AllowGet);
            }
            catch(Exception ex)
            {
                Console.WriteLine($"Exception: {ex.Message}");
                return Json("An error occurred while saving data." , JsonRequestBehavior.AllowGet);
            }
        }


        public JsonResult CheckValidUser(UserAuthModel user)
        {
            try
            {
                string result = "Fail";
                var LoginUser = dbServices.GetAllUserAuth().Where(x => x.Email == user.Email && x.Password == user.Password).SingleOrDefault();

                if(LoginUser != null)
                {
                    Session["UserID"] = LoginUser.Id.ToString();
                    Session["UserName"] = LoginUser.UserName.ToString();
                    result = "Success";

                }
                return Json(result , JsonRequestBehavior.AllowGet);
            }
            catch(Exception ex)
            {
                Console.WriteLine($"Exception: {ex.Message}");
                return Json("An error occurred while validating user." , JsonRequestBehavior.AllowGet);
            }
        }


        public ActionResult AfterLogin()
        {
            if(Session["UserID"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        public ActionResult Logout()
        {
            try
            {
                Session.Clear();
                Session.Abandon();
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                Console.WriteLine("Exception during logout: " + ex.Message);
                return View("Error");
            }

        }
            /*  public ActionResult Confirm(int regId)
              {
                  ViewBag.regId = regId;
                  return View();  
              }*/
            /*
                    public JsonResult RegisterConfirm(int regId)
                    {
                        UserAuth Data = dbServices.GetAllUserAuth().Where(x => x.Id == regId).FirstOrDefault();
                        Data.IsValid = true;
                        dbServices.AddUserAuth(Data);
                        var msg = "Your Emaill Is Verified!";
                        return Json(msg, JsonRequestBehavior.AllowGet);


                    }

                    public void BuildEmailTemplate(int regID)   
                    {
                        string body = System.IO.File.ReadAllText(HostingEnvironment.MapPath("~/EmailTemplate/") + "Text" + ".cshtml");
                       // var regInfo = dbServices.GetUserById(regID);
                        var regInfo= dbServices.GetAllUserAuth().Where(x => x.Id == regID).FirstOrDefault();

                        var url = "https://localhost:44314/" + "Resgister/Confirm?regId=" + regID;
                        body = body.Replace("@ViewBag.ConfirmationLink" , url);
                        body = body.ToString();
                        BuildEmailTemplate("Your Account Is Successfully Created" , body , regInfo.Email);

                    }

                    private void BuildEmailTemplate(string subjectText , string bodyText , string sendTo)
                    {
                        string from, to, bcc, cc, subject, body;
                        from = "rohan10bhakte0708@gmail.com";
                        to = sendTo.Trim();
                        bcc = "";
                        cc = "";
                        subject = subjectText;
                        StringBuilder sb = new StringBuilder();
                        sb.Append(bodyText);
                        body = sb.ToString();
                        MailMessage mail = new MailMessage();
                        mail.From = new MailAddress(from);
                        mail.To.Add(new MailAddress(to));
                        if(!string.IsNullOrEmpty(bcc))
                            mail.Bcc.Add(new MailAddress(bcc));
                        if
                        (!string.IsNullOrEmpty(cc))

                            mail.CC.Add(new MailAddress(cc));
                        mail.Subject = subject;
                        mail.Body = body;
                        mail.IsBodyHtml = true;
                        SendEmail(mail);
                    }*/

            /*public static void SendEmail(MailMessage mail)
            {

                SmtpClient client = new SmtpClient();
                client.Host = "smtp-gmail.com";
                client.Port = 587;
                client.EnableSsl = true;
                client.UseDefaultCredentials = false;
                client.DeliveryMethod = SmtpDeliveryMethod.Network;
                client.Credentials = new System.Net.NetworkCredential("rohan10bhakte0708@gmail.com" , "Rohan@8774");
                try
                {
                    client.Send(mail);
                }
                catch(Exception ex)
                {
                    throw ex;
                }

            }*/
        }
    }

HarrierApp/Controllers/UserPanelController.cs
using HarrierApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;

namespace HarrierApp.Controllers
{
    public class UserPanelController : Controller
    {
        DbServices dbServices = new DbServices();
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(UserModel um)
        {
            dbServices.AddUser(um);
            return RedirectToAction("Login");
        }


        [HttpGet]
        public ActionResult Login(string email)
        {
            var row=dbServices.GetUser().Where(model=> model.Email == email).FirstOrDefault();

            return View(row);
        }
        [HttpPost]
        public ActionResult Login(UserModel um)
        {
            var data = dbServices.GetUser().Where(model => model.Email == um.Email &&  model.Password == um.Password).FirstOrDefault(); 

            if (data != null)
            {
                Session["uid"] = um.Email;
                return RedirectToAction("Welcome");
            }
            else
            {
                ViewBag.ShowMsg = "Invalid Email or Password !!";
                ModelState.Clear();
            }

            return View();
        }

        public ActionResult Welcome(UserModel um)
        {
            var row = dbServices.GetUserByEmail(Session["uid"].ToString());
            return View(row);
        }



        public ActionResult Edit(int id)
        {
            var user = dbServices.GetUser().Where(model => model.Id == id).FirstOrDefault();
            if(user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        [HttpPost]
        public ActionResult Edit(UserModel user)
        {

            dbServices.UpdateUser(user);
            return RedirectToAction("Welcome");
        }




    }





}

HarrierApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
      <html>
      <head>
          <meta charset="utf-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>@ViewBag.Title - @ViewBag.ScreenTitle</title>
            @Styles.Render("~/Content/css", "~/Content/BackgroundStyle.css")
          @Scripts.Render("~/bundles/modernizr")

      </head>
    <body class="@ViewBag.BodyClass">
          <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">

              <div class="container">
                  <div class="row">
                      <div class="col">
                          @Html.ActionLink("User Auth" , "Index" , "Register" , new { area = "" } , new { @class = "navbar-brand" })
                      </div>
                      <div class="col">
                          <span class="navbar-brand">|</span>
                      </div> 
                      <div class="col">
                          @Html.ActionLink("User Login" , "Login" , "UserPanel" , new { area = "" } , new { @class = "navbar-brand" })
                      </div>
                      <div class="col">
                          <span class="navbar-brand">|</span>
                      </div>
                      <div class="col">
                          @Html.ActionLink("User" , "Index" , "User" , new { area = "" } , new { @class = "navbar-brand" })
                      </div>
                      <div class="col">
                          <span class="navbar-brand">|</span>
                      </div>
                      <div class="col">
                          @Html.ActionLink("Details" , "Index" , "Home" , new { area = "" } , new { @class = "navbar-brand" })
                      </div>
                      <div class="col">
                          <span class="navbar-brand">|</span>
                      </div>
                      <div class="col">
                          @Html.ActionLink("AddRow" , "Index" , "NewScreen" , new { area = "" } , new { @class = "navbar-brand" })
                      </div>
                  </div>

                  <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                          aria-expanded="false" aria-label="Toggle navigation">
                      <span class="navbar-toggler-icon"></span>
                  </button>
              </div>

          </nav>
          <div class="container body-content">
              @RenderBody()
              <hr />
              <footer>

              </footer>
          </div>

          @Scripts.Render("~/bundles/jquery")
          @Scripts.Render("~/bundles/bootstrap")
          @RenderSection("scripts", required: false)
      </body>
      </html>